// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Country.Data.Migrations.Country
{
    [DbContext(typeof(CountryContext))]
    [Migration("20221004201507_M1")]
    partial class M1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Country.Models.City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CityId"), 1L, 1);

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Population")
                        .HasColumnType("int");

                    b.Property<string>("ProvinceCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProvinceCode1")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CityId");

                    b.HasIndex("ProvinceCode1");

                    b.ToTable("City", (string)null);

                    b.HasData(
                        new
                        {
                            CityId = 1,
                            CityName = "Calgary",
                            Population = 1239220,
                            ProvinceCode = "AB"
                        },
                        new
                        {
                            CityId = 2,
                            CityName = "Edmonton",
                            Population = 979587,
                            ProvinceCode = "AB"
                        },
                        new
                        {
                            CityId = 3,
                            CityName = "Red Deer",
                            Population = 100418,
                            ProvinceCode = "AB"
                        },
                        new
                        {
                            CityId = 4,
                            CityName = "Vancouver",
                            Population = 631486,
                            ProvinceCode = "BC"
                        },
                        new
                        {
                            CityId = 5,
                            CityName = "Victoria",
                            Population = 367770,
                            ProvinceCode = "BC"
                        },
                        new
                        {
                            CityId = 6,
                            CityName = "Winnipeg",
                            Population = 778489,
                            ProvinceCode = "MB"
                        },
                        new
                        {
                            CityId = 7,
                            CityName = "Brandon",
                            Population = 45985,
                            ProvinceCode = "MB"
                        },
                        new
                        {
                            CityId = 8,
                            CityName = "Steinbach",
                            Population = 13245,
                            ProvinceCode = "MB"
                        });
                });

            modelBuilder.Entity("Country.Models.Province", b =>
                {
                    b.Property<string>("ProvinceCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProvinceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProvinceCode");

                    b.ToTable("Province", (string)null);

                    b.HasData(
                        new
                        {
                            ProvinceCode = "AB",
                            ProvinceName = "Alberta"
                        },
                        new
                        {
                            ProvinceCode = "BC",
                            ProvinceName = "British Columbia"
                        },
                        new
                        {
                            ProvinceCode = "MB",
                            ProvinceName = "Manitoba"
                        });
                });

            modelBuilder.Entity("Country.Models.City", b =>
                {
                    b.HasOne("Country.Models.Province", null)
                        .WithMany("Cities")
                        .HasForeignKey("ProvinceCode1");
                });

            modelBuilder.Entity("Country.Models.Province", b =>
                {
                    b.Navigation("Cities");
                });
#pragma warning restore 612, 618
        }
    }
}
